blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://community.home-assistant.io/c/third-party/node-red/31
    about: Home Assistant forums are a great place to find support and ask general questions
